# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
