# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_member_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='UID',
            field=models.CharField(default='30492034', max_length=12),
            preserve_default=False,
        ),
    ]
