# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_member_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='UID',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
